version: '3'
services:
  hadoop:
    container_name: hadoopnamenode
    image: registry.cn-hangzhou.aliyuncs.com/hzl-hadoop/hzl:register-0.0.02
    user: root
    ports:
        - "8888:8888"
    logging:
      driver: "json-file"
      options:
          max-size: "50m"
    network_mode: "host"